environment:
- !secret 'gAAAAABYyBOPvTTuVOQmmalewqyh4Z9ghnhD-dH5of2aVIXHvoSz-deYNG2a0nSAYZqdLlYVeMOBWPAypO1xLprsvRk-4C1VXWDHsorgvwY12udyygCVnBA='
- refs/heads/kalbir-test-mp:
  - !secret 'gAAAAABYyBOP2KBA6lRYaszD9vTrYGKwC42ib_hSjZYzXlWPiPi7KfP2a2K7xfMYjCaVmH1yDl3ys7OcGlCcQqqrZI3Opg-cjpuYsAhnIL5RGd--NGPTPuo='
- refs/heads/bt-mp-test-1:
  - !secret 'gAAAAABYyBOP-qIHeUpTtq9VX4kc2Bm4-dDVZHwz5cIvCMkeJJmQ9qRNHY_e4U_83_rDTd8WmgU-uUC3iQZFCRrW5JpKExEsaVAdtdeS54dMfj5OqKIBqtw='
  - bonus=yolo
installation_id: '10948'
repo_id: '50422368'
