environment:
- test=37
- !secret 'gAAAAABYwWdgOENdO76z5jt-qMo-w6Kwu1oQC_wne6MVhK8XWBUjK9KkKffdpQsEkPUxYytaaEF2McaAkq6KT8hgGDOjcw3vgDZ9gYBB0Ti6_PHTkzOtDV8='
- !secret 'gAAAAABYwWdgS9CJL30HP7iN1SphjSWXiV6dXWyooGqIKvSRk99-PnhbHbBaNLsIZqtXy69yDd9Kjalejtm1-BHxCMXXySYxZFbnyKlAmhcNQNgxasbflLY='
- master:
  - !secret 'gAAAAABYwWdgb4ELi_q0XNnYhe05M9u_pe113PIoBjV_Nnna_uLdw6Rj1NrWeGtDEMRNl4ozVqgH69yyT7_BXu16hT31OfAJzchZQW0i9ytAYb9xJKFeLFw='
- bt-mp-test-1:
  - !secret 'gAAAAABYwWdg6xNi9hrDmJm6CfYsslQs8xiFngF4KsBLGB9iXjP6TgWRDKjMCLSioZb8GoDp4LrJu1dgT_OHHRtvwawSl-iOeVfWKmXweMpGWWdMwZKC4p8='
installation_id: '10948'
repo_id: '50422368'
