environment:
- !secret 'gAAAAABYxryACXl6eQnrep4E20rdy8Xvg_ezGP2ovhBJo_VTfiXgjZzDiZfA9wWlmsFUUFjAkZqOTKqZs86WiNGxTVF9gAj6TQ=='
- refs/heads/kalbir-test-mp:
  - !secret 'gAAAAABYxryAGFoos7eMjh7XMx2JrMp8l6fO85hh46HpPj2xqfkrhflaSHLqV9TEXiCVvAMXC6R444RJzFymWousu4XpaAnR0g=='
installation_id: '10948'
repo_id: '50422368'
