environment:
- !secret 'gAAAAABYx7kRwqar2FKdlr5DBGpkJHjcxXzLBD_TdcGSImC16ppar6evukoh_MQrnof1EMRSMAsMCwmPVthbpELPUDw9xDvvzQ=='
- refs/heads/kalbir-test-mp:
  - test=25
  - !secret 'gAAAAABYx7kRiOPyA1mQKhx6Hh3HfTYtuIOJ694bvrQ0-4oNxh7lJZn4UoOLOxsL1yIspj8rtgRI9jC6NAFEyEl6MBR6B8RePg=='
installation_id: '10948'
repo_id: '50422368'
