environment:
- !secret 'gAAAAABYx65YltrqQdnHPkYF4tIU17T1JJ38yjwVxzMiv27XCknbfPuhd6kAIqeErD37H-ld6iNtsgoIFcjaknAW5Ym3aLpYnQ=='
- refs/heads/kalbir-test-mp:
  - test=24
  - !secret 'gAAAAABYx65Y9oXuTirsI1siookRl_a9KTDd-1s1AfwvxyIQMW6NnjOmlG6XH0jCjUJha5BUqnofblvDWMjHCkIOcjcKBL9cEg=='
installation_id: '10948'
repo_id: '50422368'
